import CV from "../../cv"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Michał Porydzaj CV – AI Systems Architect & Principal Software Engineer | Tear Company",
  description:
    "Michał Porydzaj - Technical Leader, AI Systems Architect, and Principal Software Engineer with 10+ years experience. Creator of Miriam, Weemah, and innovative GPT-based AI systems. Expert in TypeScript, React, Next.js, ethical AI development, and developer experience optimization.",
  keywords: [
    "Michał Porydzaj",
    "AI Systems Architect",
    "Principal Software Engineer",
    "Technical Leader",
    "AI expert Poland",
    "GPT developer",
    "custom GPT creator",
    "AI consultant",
    "ethical AI developer",
    "TypeScript expert",
    "React developer",
    "Next.js specialist",
    "Node.js expert",
    "fullstack developer",
    "AI presence engine",
    "developer experience",
    "DX advocate",
    "system architecture",
    "microservices architect",
    "legacy system refactoring",
    "CI/CD optimization",
    "DevOps engineer",
    "technical audit",
    "AI coaching",
    "Miriam AI",
    "Weemah AI",
    "Imago Dei Akademia",
    "Teardrop AI",
    "symbolic UX",
    "ritual design",
    "conversational AI",
    "human-centered AI",
    "AI transformation",
    "AI innovation",
    "machine learning",
    "NLP systems",
    "OpenAI GPT",
    "AI architecture",
    "prompt engineering",
    "AI product development",
    "startup CTO",
    "tech lead",
    "senior software engineer",
    "programming expert",
    "code optimization",
    "performance tuning",
    "scalable systems",
    "software consultant",
    "technical mentor",
    "Poland developer",
    "Silesia tech",
    "European AI expert",
    "remote work specialist",
    "agile development",
    "clean architecture",
    "test-driven development",
    "TDD",
    "software craftsmanship",
    "digital transformation",
    "enterprise software"
  ],
  openGraph: {
    title: "Michał Porydzaj – AI Systems Architect & Principal Software Engineer",
    description:
      "Technical Leader with 10+ years experience in AI systems, scalable architecture, and developer experience. Creator of innovative GPT-based AI projects: Miriam, Weemah, Imago Dei Akademia, and Teardrop. Expert in TypeScript, React, ethical AI development.",
    url: "https://tearcompany.com/cv",
    siteName: "Tear Company",
    images: [
      {
        url: "/cv-profile.png",
        width: 1200,
        height: 1200,
        alt: "Michał Porydzaj – AI Systems Architect and Principal Software Engineer",
      },
    ],
    locale: "en_US",
    type: "profile",
  },
  twitter: {
    card: "summary_large_image",
    title: "Michał Porydzaj – AI Systems Architect & Principal Software Engineer",
    description:
      "Technical Leader specializing in AI systems, ethical GPT development, and scalable architecture. Creator of Miriam, Weemah, and innovative AI presence engines. 10+ years experience in fullstack development.",
    images: ["/cv-profile.png"],
  },
  alternates: {
    canonical: "https://tearcompany.com/cv",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  authors: [{ name: "Michał Porydzaj", url: "https://tearcompany.com" }],
  creator: "Michał Porydzaj",
  publisher: "Tear Company",
  category: "Technology",
}

export default function CVPage() {
  return <CV />
}
